baseurl = "https://ghaffarbajwa9.github.io/hugo/."
name = "AMP"
description = "This is amp site"
publishDir = "docs"
homepage = "https://github.com/ghaffarbajwa9/hugo"
tags = ["blog", "portfolio", "AMP", "Material Design"]
features = ["AMP","Material Design","Google Analytics","Menu","Tags","Categories","Social links"]

[author]
  name = "abdul"
  homepage = "https://github.com/ghaffarbajwa9/hugo"
